### ISSUE TITLE
Example of the argument "subset_path"

### ISSUE THREAD

**Issue by cmhungsteve** [diffusion-classifier/diffusion-classifier#13]
Can you provide some examples to explain how to set the argument "subset_path"?
For example, if I just want to test the first 10 testing images in CIFAR 10, how to do it?

Thank you.

**Comment by alexlioralexli** [comment]
You should make a numpy file with the indices that you want to evaluate, like this: 
```python3
import numpy as np
np.save('pets_first_10.npy', np.arange(10))
```
And then you should add ` --subset_path pets_first_10.npy` to your command.

**Comment by cmhungsteve** [comment]
It works.
Thank you.
