### ISSUE TITLE
Question about the code running speed

### ISSUE THREAD

**Issue by liuhui0401** [diffusion-classifier/diffusion-classifier#15]
I tried to run the code on a single A100 as described in the Readme. It took me 30s to deal with a single image. Since Cifar10 has 10000 test images, it would take me 83h to finish the whole process. Is it normal? Is there any way to speed it up? Thank you!

**Comment by alexlioralexli** [comment]
This is roughly the runtime I'd expect. Here are some things I'd try: 
- Increase the batch size. We didn't try our code with A100s, so perhaps it's not fully utilizing the GPU. 
- Add these lines to the code, which I think only work with A100 or newer GPUs: 
  - I don't have an A100 so I can't verify that this helps, but other repos have mentioned speedups. 
```python 
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.allow_tf32 = True
```

- Reduce the number of evaluations per class. 
```bash
python eval_prob_adaptive.py --dataset cifar10 --split test --n_trials 1 \
  --to_keep 5 1 --n_samples 25 250 --loss l1 \
  --prompt_path prompts/cifar10_prompts.csv
  ```
  This should be twice as fast and almost as accurate (within 0.3% on CIFAR-10 in this case). Overall, inference is indeed quite slow, and we think improving it is an exciting research direction!
