### ISSUE TITLE
Example about multiple workers 

### ISSUE THREAD

**Issue by umnooob** [diffusion-classifier/diffusion-classifier#16]
Thanks for your impressive work！

I noticed you have mentioned  `--n_workers` and `--worker_idx` options. In the code, they just split the dataset.
I'm wondering how I use them since the inference speed is relatively slow (maybe using multiprocessing?). And whether it will be better if using multi GPU?

Could you please give an example about the options :)

**Comment by alexlioralexli** [comment]
I used these options to split inference across separate jobs, potentially across multiple machines. Here's an example use case if you had 2 separate computers (or slurm jobs), each with 1 gpu. 

On the first computer: 
```bash
python eval_prob_adaptive.py --dataset cifar10 --split test --n_trials 1 \
  --to_keep 5 1 --n_samples 50 500 --loss l1 \
  --prompt_path prompts/cifar10_prompts.csv \
  --n_workers 2 --worker_idx 0
  ```

On the second computer: 
  ```bash
python eval_prob_adaptive.py --dataset cifar10 --split test --n_trials 1 \
  --to_keep 5 1 --n_samples 50 500 --loss l1 \
  --prompt_path prompts/cifar10_prompts.csv \
  --n_workers 2 --worker_idx 1
  ```
These commands would split the inference work 50-50 across the two runs. If I ran these commands on separate computers, I would then combine their logging folders before using `scripts/print_acc.py` to get the accuracy on the full dataset.
