### ISSUE TITLE
Question about the inference hyper-parameters

### ISSUE THREAD

**Issue by Carlofkl** [diffusion-classifier/diffusion-classifier#18]
I see the  'Prompts kept per stage' and 'Evaluations per stage' in the paper, like '5 1' and '50 500' for CIFAR10, and the diffusion-classifier get the high score of 88.5. So I'm curious about the exact hyper-parameters about the inference of CIFAR10 and STL10. Thanks a lot!

**Comment by alexlioralexli** [comment]
The exact commands to reproduce our zero-shot Diffusion Classifier results are all in `commands.md`. Could you clarify what you're looking for?

**Comment by Carlofkl** [comment]
Thanks a lot. 
The inference is still running and the accuracy now is a little bit lower than the result in your paper. I'll see it again after it finished, thanks a lot anyway!
