### ISSUE TITLE
Question about results of cifar 100 dataset

### ISSUE THREAD

**Issue by JamesSand** [diffusion-classifier/diffusion-classifier#19]
Hello, thanks for the great work! I was wondering if you have some insights on how well the model performs on CIFAR100, or if there is a set of hyperparameters that work well under this setting? Thank you!!

**Comment by alexlioralexli** [comment]
I was able to get 67.73% on CIFAR-100 with the prompts I just uploaded to `prompts/cifar100_blurry_prompts.csv`. These use a better template, based on what CLIP uses. 

Here's the command I used to run SD 2.0 with l1 loss on CIFAR-100: 
```bash
python eval_prob_adaptive.py --dataset cifar100 --split test --n_trials 1 --version 2-0 --loss l1 \
             --to_keep 20 10 5 1 --n_samples 20 50 100 500 --prompt_path prompts/cifar100_blurry_prompts.csv 
```

Let me know if you have any other questions!
