### ISSUE TITLE
Error on loading 'diffusion/imagenet_class_index.json'

### ISSUE THREAD

**Issue by beotborry** [diffusion-classifier/diffusion-classifier#21]
First of all, thank you for your interesting work!

I tried to execute the evaluation code but it seems that there is an error on loading 'diffusion/imagenet_class_index.json' file.

https://github.com/diffusion-classifier/diffusion-classifier/blob/3cd7f0c18b34ca8685f99d76db2f0cff282db107/diffusion/datasets.py#L34

Could you let me know that where can I find the json file?

Thank you in advance

**Comment by alexlioralexli** [comment]
Sorry about that! I just uploaded the file. Let me know if there are any remaining issues!
