### ISSUE TITLE
The diffusion.datasets package in print_dit_acc.py

### ISSUE THREAD

**Issue by hadwinn** [diffusion-classifier/diffusion-classifier#22]
conda env create -f environment.yml execution complete, but:

(diffusion-classifier) ➜  diffusion-classifier git:(master) ✗ python scripts/print_dit_acc.py data/imagenet_dit256 --dataset imagenet
Traceback (most recent call last):
  File "/home/featurize/work/diffusion-classifier/scripts/print_dit_acc.py", line 5, in <module>
    from diffusion.datasets import get_target_dataset, IMAGENET_A_CLASSES
ModuleNotFoundError: No module named 'diffusion'

What's the problem?

**Comment by alexlioralexli** [comment]
You need to add the `diffusion-classifier` directory to your PYTHONPATH
