### ISSUE TITLE
About test samples for computing accuracy

### ISSUE THREAD

**Issue by aniket004** [diffusion-classifier/diffusion-classifier#24]
Hi,

Congrats for the impressive work. The inference speed is quite slow though, and it was mentioned "for computational reasons, we evaluated on 4 images per class (4000 test images total)." I am wondering if this protocol has been adpoted for all the datasets (Food, pets, cifar10, aircraft, flowers, stl10). For Imagenet, it was mentioned that the test set is 2000 images. The clarification would be much appreciated. 

Thanks,
Aniket.

**Comment by alexlioralexli** [comment]
We used the full test set for all other datasets.
