### ISSUE TITLE
About CUDA and xformers

### ISSUE THREAD

**Issue by CharlesTran** [diffusion-classifier/diffusion-classifier#26]
My GPU is RTX 3080 and CUDA is 11.3. However xformers require CUDA>=11.8, how can I solve this problem?

**Comment by alexlioralexli** [comment]
Does the code run if you remove xformers from the conda env?

**Comment by CharlesTran** [comment]
No, it will break at line 28 of diffusion/models.py
![2024-04-17 192622](https://github.com/diffusion-classifier/diffusion-classifier/assets/59631254/53292b6f-0f14-41ef-aae9-1ac8c64a5b4d)

**Comment by alexlioralexli** [comment]
Can you comment out the line in `get_sd_model` that uses xformers?

**Comment by CharlesTran** [comment]
Yes it works, thanks very much.
