### ISSUE TITLE
diffusion

### ISSUE THREAD

**Issue by sss777-888** [diffusion-classifier/diffusion-classifier#28]
Is Stable Diffusion 2.0 the kind of diffuse single-step generation of images you are using? Or is it a diffusion multi-step generation

**Comment by alexlioralexli** [comment]
If I'm understanding the question correctly: when used for generation, Stable Diffusion 2.0 requires multiple steps for a sample. 

For our method, however, we don't need to chain together denoising steps.

**Comment by sss777-888** [comment]
> If I'm understanding the question correctly: when used for generation, Stable Diffusion 2.0 requires multiple steps for a sample.
> 
> For our method, however, we don't need to chain together denoising steps.

Is it possible to change SD2.0 to sdxl-turbo in Adversarial Diffusion Distillation?
The above paper is a single-step generation of images, and the SD2.0 you use is to generate images in multiple steps using UNET, but your method only uses UNET once for each noisy image to predict the noise, do I understand correctly?

**Comment by alexlioralexli** [comment]
- I'm not sure how well it would work, but it'd be super interesting if it does well!
- We use the UNet multiple times per image and per class, since we add multiple noises at different scales which gives us multiple noisy images.
