### ISSUE TITLE
Data Normalization 

### ISSUE THREAD

**Issue by mohammad-yousuf** [diffusion-classifier/diffusion-classifier#29]
I just wanted to know how you are normalizing data below:

```
def _convert_image_to_rgb(image):
    return image.convert("RGB")

def get_transform(interpolation=InterpolationMode.BICUBIC, size=512):
    transform = torch_transforms.Compose([
        torch_transforms.Resize(size, interpolation=interpolation),
        torch_transforms.CenterCrop(size),
        _convert_image_to_rgb,
        torch_transforms.ToTensor(),
        torch_transforms.Normalize([0.5], [0.5])
    ])
    return transform
```

In this code you are converting image to RGB and applying grayscale normalization? Please clarify if I'm missing something here.

**Comment by alexlioralexli** [comment]
Yes, this is the transformation I'm applying. Note that [0.5] is broadcasted to [0.5, 0.5, 0.5] and normalizes each color channel by the same amount. This is what the SD VAE expects.
