### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by BingliangLi** [diffusion-classifier/diffusion-classifier#3]
Dear authors:

I'm very interested in your work, and looking forward to use it in my research. So I would like to ask is there a specific timeline for the code release, and is it possible that the code will be released in the next two weeks?

Really looking forward to the release :)

**Comment by alexlioralexli** [comment]
We have just released the code for zero-shot classification with Stable Diffusion. Let me know if you have any other questions!
