### ISSUE TITLE
conda env create takes forever, anyone has the same issue?

### ISSUE THREAD

**Issue by zzou-cn** [diffusion-classifier/diffusion-classifier#8]
Here's some of the debug output from conda, how can I resolve this? Any help is appreciated!

DEBUG conda.resolve:solve(1346): Solve: minimize removed packages
DEBUG conda.resolve:solve(1353): Solve: maximize versions of requested packages
DEBUG conda.common._logic:_run_sat(607): Invoking SAT with clause count: 432932
DEBUG conda.common._logic:minimize(745): Final peak objective: 0
DEBUG conda.common._logic:_run_sat(607): Invoking SAT with clause count: 433887
DEBUG conda.common._logic:minimize(745): Final peak objective: 0
DEBUG conda.resolve:solve(1357): Initial package channel/version metric: 0/0
DEBUG conda.resolve:solve(1360): Solve: minimize track_feature count
DEBUG conda.resolve:generate_feature_count(933): generate_feature_count returning with clause count: 435425
DEBUG conda.common._logic:minimize(658): Clauses added, recomputing solution
DEBUG conda.common._logic:_run_sat(607): Invoking SAT with clause count: 435425
DEBUG conda.common._logic:_run_sat(607): Invoking SAT with clause count: 435447
DEBUG conda.common._logic:minimize(745): Final sum objective: 0
DEBUG conda.resolve:solve(1363): Track feature count: 0
DEBUG conda.common._logic:minimize(664): Empty objective, trivial solution
DEBUG conda.resolve:solve(1374): Package misfeature count: 0
DEBUG conda.resolve:solve(1377): Solve: maximize build numbers of requested packages
DEBUG conda.common._logic:_run_sat(607): Invoking SAT with clause count: 435608
DEBUG conda.common._logic:minimize(745): Final peak objective: 0
DEBUG conda.resolve:solve(1379): Initial package build metric: 0
DEBUG conda.resolve:solve(1382): Solve: prefer arch over noarch for requested packages
DEBUG conda.common._logic:minimize(664): Empty objective, trivial solution
DEBUG conda.resolve:solve(1384): Noarch metric: 0
DEBUG conda.resolve:solve(1388): Solve: minimize number of optional installations
DEBUG conda.common._logic:minimize(664): Empty objective, trivial solution
DEBUG conda.resolve:solve(1391): Optional package install metric: 0
DEBUG conda.resolve:solve(1394): Solve: minimize number of necessary upgrades
DEBUG conda.common._logic:minimize(664): Empty objective, trivial solution
DEBUG conda.resolve:solve(1397): Dependency update count: 0
DEBUG conda.resolve:solve(1400): Solve: maximize versions and builds of indirect dependencies.  Prefer arch over noarch where equivalent.
DEBUG conda.common._logic:_run_sat(607): Invoking SAT with clause count: 455945
DEBUG conda.common._logic:_run_sat(607): Invoking SAT with clause count: 435611
DEBUG conda.common._logic:_run_sat(607): Invoking SAT with clause count: 438652
DEBUG conda.common._logic:minimize(745): Final peak objective: 1
DEBUG conda.common._logic:_run_sat(607): Invoking SAT with clause count: 10576976
DEBUG conda.common._logic:_run_sat(607): Invoking SAT with clause count: 4038608
DEBUG conda.common._logic:_run_sat(607): Invoking SAT with clause count: 1975208
DEBUG conda.common._logic:_run_sat(607): Invoking SAT with clause count: 1250750

**Comment by alexlioralexli** [comment]
It's hard for me to tell, but maybe one of these will work: 
```
conda config --set channel_priority strict
conda env create -f environment.yml
```
or 
```
conda config --set channel_priority flexible
conda env create -f environment.yml
```
Let me know if that fixes your problem.

**Comment by zzou-cn** [comment]
I tried the strict channel priority and it gives me some new errors, seems like there is conflict in the dependency?

Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
DEBUG conda.resolve:get_reduced_index(669): Retrieving packages for: 
  - pytorch[version='>=1.11.0']
DEBUG conda.resolve:filter_group(744): pytorch: pruned from 264 -> 97
DEBUG conda.resolve:filter_group(744): blas: pruned from 104 -> 30
DEBUG conda.resolve:filter_group(744): _openmp_mutex: pruned from 6 -> 3
DEBUG conda.resolve:filter_group(744): _libgcc_mutex: pruned from 3 -> 1
DEBUG conda.resolve:filter_group(744): llvm-openmp: pruned from 32 -> 28
DEBUG conda.resolve:filter_group(744): python: pruned from 328 -> 205
DEBUG conda.resolve:filter_group(744): pip: pruned from 124 -> 67
DEBUG conda.resolve:filter_group(744): setuptools: pruned from 833 -> 537
DEBUG conda.resolve:filter_group(744): wheel: pruned from 79 -> 33
DEBUG conda.resolve:filter_group(744): typing_extensions: pruned from 49 -> 29
DEBUG conda.resolve:get_reduced_index(669): Retrieving packages for: 
  - python=3.9
DEBUG conda.resolve:filter_group(744): python: pruned from 328 -> 43
DEBUG conda.resolve:filter_group(744): pip: pruned from 124 -> 45
DEBUG conda.resolve:filter_group(744): setuptools: pruned from 833 -> 132
DEBUG conda.resolve:filter_group(744): wheel: pruned from 79 -> 14
DEBUG conda.resolve:get_reduced_index(669): Retrieving packages for: 
  - seaborn
DEBUG conda.resolve:filter_group(744): numpy: pruned from 573 -> 562
DEBUG conda.resolve:filter_group(744): python: pruned from 328 -> 320
DEBUG conda.resolve:get_reduced_index(669): Retrieving packages for: 
  - pip
DEBUG conda.resolve:filter_group(744): python: pruned from 328 -> 320
DEBUG conda.resolve:get_reduced_index(669): Retrieving packages for: 
  - @/linux-64::__unix==0=0
DEBUG conda.resolve:get_reduced_index(669): Retrieving packages for: 
  - transformers[version='>=4.14.1']
DEBUG conda.resolve:filter_group(744): transformers: pruned from 81 -> 35
DEBUG conda.resolve:filter_group(744): python: pruned from 328 -> 263
DEBUG conda.resolve:filter_group(744): pip: pruned from 124 -> 89
DEBUG conda.resolve:filter_group(744): setuptools: pruned from 833 -> 659
DEBUG conda.resolve:filter_group(744): wheel: pruned from 79 -> 52
DEBUG conda.resolve:filter_group(744): filelock: pruned from 40 -> 35
DEBUG conda.resolve:filter_group(744): requests: pruned from 100 -> 49
DEBUG conda.resolve:filter_group(744): tqdm: pruned from 150 -> 107
DEBUG conda.resolve:filter_group(744): numpy: pruned from 573 -> 395
DEBUG conda.resolve:filter_group(744): packaging: pruned from 24 -> 18
DEBUG conda.resolve:filter_group(744): pytorch: pruned from 264 -> 260
DEBUG conda.resolve:filter_group(744): blas: pruned from 104 -> 30
DEBUG conda.resolve:filter_group(744): _openmp_mutex: pruned from 6 -> 3
DEBUG conda.resolve:filter_group(744): _libgcc_mutex: pruned from 3 -> 1
DEBUG conda.resolve:filter_group(744): llvm-openmp: pruned from 32 -> 28
DEBUG conda.resolve:filter_group(744): pyyaml: pruned from 128 -> 106
DEBUG conda.resolve:filter_group(744): regex: pruned from 518 -> 394
DEBUG conda.resolve:filter_group(744): click: pruned from 81 -> 73
DEBUG conda.resolve:filter_group(744): joblib: pruned from 37 -> 23
DEBUG conda.resolve:filter_group(744): six: pruned from 32 -> 19
DEBUG conda.resolve:filter_group(744): tokenizers: pruned from 98 -> 68
DEBUG conda.resolve:filter_group(744): libgcc-ng: pruned from 106 -> 71
DEBUG conda.resolve:filter_group(744): libstdcxx-ng: pruned from 108 -> 71
DEBUG conda.resolve:filter_group(744): python_abi: pruned from 33 -> 20
DEBUG conda.resolve:filter_group(744): tqdm: pruned from 107 -> 76
DEBUG conda.resolve:filter_group(744): python: pruned from 263 -> 251
DEBUG conda.resolve:filter_group(744): setuptools: pruned from 659 -> 549
DEBUG conda.resolve:filter_group(744): numpy: pruned from 395 -> 243
DEBUG conda.resolve:filter_group(744): libblas: pruned from 112 -> 107
DEBUG conda.resolve:filter_group(744): libcblas: pruned from 112 -> 107
DEBUG conda.resolve:filter_group(744): blas: pruned from 30 -> 29
DEBUG conda.resolve:filter_group(744): pyyaml: pruned from 106 -> 90
DEBUG conda.resolve:filter_group(744): regex: pruned from 394 -> 341
DEBUG conda.resolve:filter_group(744): click: pruned from 73 -> 57
DEBUG conda.resolve:get_reduced_index(669): Retrieving packages for: 
  - @/linux-64::__cuda==11.4=0
DEBUG conda.resolve:get_reduced_index(669): Retrieving packages for: 
  - tqdm
DEBUG conda.resolve:get_reduced_index(669): Retrieving packages for: 
  - @/linux-64::__linux==4.15.0=0
DEBUG conda.resolve:get_reduced_index(669): Retrieving packages for: 
  - diffusers
DEBUG conda.resolve:filter_group(744): python: pruned from 328 -> 263
DEBUG conda.resolve:filter_group(744): pip: pruned from 124 -> 89
DEBUG conda.resolve:filter_group(744): setuptools: pruned from 833 -> 659
DEBUG conda.resolve:filter_group(744): wheel: pruned from 79 -> 52
DEBUG conda.resolve:filter_group(744): requests: pruned from 100 -> 49
DEBUG conda.resolve:filter_group(744): tqdm: pruned from 150 -> 107
DEBUG conda.resolve:filter_group(744): importlib-metadata: pruned from 275 -> 271
DEBUG conda.resolve:filter_group(744): numpy: pruned from 573 -> 395
DEBUG conda.resolve:filter_group(744): pillow: pruned from 337 -> 262
DEBUG conda.resolve:filter_group(744): pytorch: pruned from 264 -> 260
DEBUG conda.resolve:filter_group(744): blas: pruned from 104 -> 30
DEBUG conda.resolve:filter_group(744): _openmp_mutex: pruned from 6 -> 3
DEBUG conda.resolve:filter_group(744): _libgcc_mutex: pruned from 3 -> 1
DEBUG conda.resolve:filter_group(744): llvm-openmp: pruned from 32 -> 28
DEBUG conda.resolve:filter_group(744): regex: pruned from 518 -> 394
DEBUG conda.resolve:filter_group(744): filelock: pruned from 40 -> 35
DEBUG conda.resolve:filter_group(744): numpy: pruned from 395 -> 297
DEBUG conda.resolve:filter_group(744): libblas: pruned from 112 -> 107
DEBUG conda.resolve:filter_group(744): libcblas: pruned from 112 -> 107
DEBUG conda.resolve:filter_group(744): libgcc-ng: pruned from 106 -> 104
DEBUG conda.resolve:filter_group(744): blas: pruned from 30 -> 29
DEBUG conda.resolve:get_reduced_index(669): Retrieving packages for: 
  - accelerate
DEBUG conda.resolve:filter_group(744): numpy: pruned from 573 -> 263
DEBUG conda.resolve:filter_group(744): libblas: pruned from 112 -> 108
DEBUG conda.resolve:filter_group(744): libcblas: pruned from 112 -> 108
DEBUG conda.resolve:filter_group(744): _libgcc_mutex: pruned from 3 -> 2
DEBUG conda.resolve:filter_group(744): liblapack: pruned from 81 -> 77
DEBUG conda.resolve:filter_group(744): python: pruned from 328 -> 263
DEBUG conda.resolve:filter_group(744): pip: pruned from 124 -> 89
DEBUG conda.resolve:filter_group(744): setuptools: pruned from 833 -> 659
DEBUG conda.resolve:filter_group(744): wheel: pruned from 79 -> 52
DEBUG conda.resolve:filter_group(744): packaging: pruned from 24 -> 18
DEBUG conda.resolve:filter_group(744): pytorch: pruned from 264 -> 260
DEBUG conda.resolve:filter_group(744): blas: pruned from 104 -> 30
DEBUG conda.resolve:filter_group(744): _openmp_mutex: pruned from 6 -> 3
DEBUG conda.resolve:filter_group(744): _libgcc_mutex: pruned from 2 -> 1
DEBUG conda.resolve:filter_group(744): llvm-openmp: pruned from 32 -> 28
DEBUG conda.resolve:filter_group(744): pyyaml: pruned from 128 -> 106
DEBUG conda.resolve:filter_group(744): libblas: pruned from 108 -> 107
DEBUG conda.resolve:filter_group(744): libcblas: pruned from 108 -> 107
DEBUG conda.resolve:filter_group(744): libgcc-ng: pruned from 106 -> 104
DEBUG conda.resolve:filter_group(744): liblapack: pruned from 77 -> 76
DEBUG conda.resolve:filter_group(744): blas: pruned from 30 -> 29
DEBUG conda.resolve:get_reduced_index(669): Retrieving packages for: 
  - xformers::xformers
DEBUG conda.resolve:filter_group(744): xformers: pruned from 15 -> 0
DEBUG conda.resolve:get_reduced_index(669): Retrieving packages for: 
  - torchvision[version='>=0.12.0']
DEBUG conda.resolve:filter_group(744): torchvision: pruned from 291 -> 93
DEBUG conda.resolve:filter_group(744): bzip2: pruned from 9 -> 5
DEBUG conda.resolve:filter_group(744): _libgcc_mutex: pruned from 3 -> 2
DEBUG conda.resolve:filter_group(744): freetype: pruned from 28 -> 8
DEBUG conda.resolve:filter_group(744): libpng: pruned from 25 -> 8
DEBUG conda.resolve:filter_group(744): gmp: pruned from 14 -> 8
DEBUG conda.resolve:filter_group(744): gnutls: pruned from 16 -> 5
DEBUG conda.resolve:filter_group(744): nettle: pruned from 13 -> 6
DEBUG conda.resolve:filter_group(744): openh264: pruned from 12 -> 2
DEBUG conda.resolve:filter_group(744): libgcc-ng: pruned from 106 -> 103
DEBUG conda.resolve:filter_group(744): libstdcxx-ng: pruned from 108 -> 104
DEBUG conda.resolve:filter_group(744): zlib: pruned from 25 -> 22
DEBUG conda.resolve:filter_group(744): numpy: pruned from 573 -> 496
DEBUG conda.resolve:filter_group(744): python: pruned from 328 -> 318
DEBUG conda.resolve:filter_group(744): pillow: pruned from 337 -> 240
DEBUG conda.resolve:filter_group(744): libtiff: pruned from 45 -> 36
DEBUG conda.resolve:filter_group(744): xz: pruned from 10 -> 8
DEBUG conda.resolve:filter_group(744): python: pruned from 318 -> 304
DEBUG conda.resolve:filter_group(744): pip: pruned from 124 -> 121
DEBUG conda.resolve:filter_group(744): setuptools: pruned from 833 -> 798
DEBUG conda.resolve:filter_group(744): wheel: pruned from 79 -> 78
DEBUG conda.resolve:filter_group(744): tk: pruned from 25 -> 15
DEBUG conda.resolve:filter_group(744): python: pruned from 304 -> 205
DEBUG conda.resolve:filter_group(744): pip: pruned from 121 -> 67
DEBUG conda.resolve:filter_group(744): setuptools: pruned from 798 -> 537
DEBUG conda.resolve:filter_group(744): wheel: pruned from 78 -> 33
DEBUG conda.resolve:filter_group(744): pytorch: pruned from 264 -> 97
DEBUG conda.resolve:filter_group(744): blas: pruned from 104 -> 30
DEBUG conda.resolve:filter_group(744): _openmp_mutex: pruned from 6 -> 3
DEBUG conda.resolve:filter_group(744): _libgcc_mutex: pruned from 2 -> 1
DEBUG conda.resolve:filter_group(744): llvm-openmp: pruned from 32 -> 28
DEBUG conda.resolve:filter_group(744): typing_extensions: pruned from 49 -> 29
DEBUG conda.resolve:filter_group(744): requests: pruned from 100 -> 28
DEBUG conda.resolve:filter_group(744): certifi: pruned from 171 -> 80
DEBUG conda.resolve:filter_group(744): urllib3: pruned from 100 -> 43
DEBUG conda.resolve:filter_group(744): pysocks: pruned from 56 -> 26
DEBUG conda.resolve:filter_group(744): libgcc-ng: pruned from 103 -> 102
DEBUG conda.resolve:filter_group(744): numpy: pruned from 496 -> 245
DEBUG conda.resolve:filter_group(744): libblas: pruned from 112 -> 107
DEBUG conda.resolve:filter_group(744): libcblas: pruned from 112 -> 107
DEBUG conda.resolve:filter_group(744): pillow: pruned from 240 -> 181
DEBUG conda.resolve:filter_group(744): blas: pruned from 30 -> 29
DEBUG conda.resolve:get_reduced_index(669): Retrieving packages for: 
  - numpy
DEBUG conda.resolve:filter_group(744): python: pruned from 328 -> 320
DEBUG conda.resolve:get_reduced_index(669): Retrieving packages for: 
  - ipykernel
DEBUG conda.resolve:filter_group(744): ipykernel: pruned from 347 -> 302
DEBUG conda.resolve:filter_group(744): ipython: pruned from 334 -> 297
DEBUG conda.resolve:filter_group(744): pickleshare: pruned from 32 -> 30
DEBUG conda.resolve:filter_group(744): python: pruned from 328 -> 320
DEBUG conda.resolve:get_reduced_index(669): Retrieving packages for: 
  - wandb
DEBUG conda.resolve:filter_group(744): click: pruned from 81 -> 69
DEBUG conda.resolve:filter_group(744): docker-pycreds: pruned from 15 -> 1
DEBUG conda.resolve:filter_group(744): psutil: pruned from 179 -> 164
DEBUG conda.resolve:filter_group(744): python: pruned from 328 -> 317
DEBUG conda.resolve:filter_group(744): pip: pruned from 124 -> 121
DEBUG conda.resolve:filter_group(744): setuptools: pruned from 833 -> 798
DEBUG conda.resolve:filter_group(744): wheel: pruned from 79 -> 78
DEBUG conda.resolve:filter_group(744): pyyaml: pruned from 128 -> 126
DEBUG conda.resolve:filter_group(744): requests: pruned from 100 -> 93
DEBUG conda.resolve:filter_group(744): certifi: pruned from 171 -> 163
DEBUG conda.resolve:filter_group(744): urllib3: pruned from 100 -> 97
DEBUG conda.resolve:filter_group(744): six: pruned from 32 -> 30
DEBUG conda.resolve:filter_group(744): gitpython: pruned from 61 -> 57
DEBUG conda.resolve:get_reduced_index(669): Retrieving packages for: 
  - cuda-nvcc
DEBUG conda.resolve:get_reduced_index(669): Retrieving packages for: 
  - tensorboard
DEBUG conda.resolve:filter_group(744): python: pruned from 328 -> 320
DEBUG conda.resolve:get_reduced_index(669): Retrieving packages for: 
  - @/linux-64::__archspec==1=x86_64
DEBUG conda.resolve:get_reduced_index(669): Retrieving packages for: 
  - @/linux-64::__glibc==2.31=0
DEBUG conda.resolve:get_reduced_index(669): Retrieving packages for: 
  - pytest
DEBUG conda.resolve:filter_group(744): python: pruned from 328 -> 320
DEBUG conda.resolve:get_reduced_index(669): Retrieving packages for: 
  - pytest-env
DEBUG conda.resolve:filter_group(744): python: pruned from 328 -> 320
DEBUG conda.resolve:get_reduced_index(669): Retrieving packages for: 
  - nvidia::cudatoolkit
DEBUG conda.resolve:get_reduced_index(669): Retrieving packages for: 
  - flake8
DEBUG conda.resolve:get_reduced_index(669): Retrieving packages for: 
  - ipdb
DEBUG conda.resolve:filter_group(744): ipython: pruned from 334 -> 297
DEBUG conda.resolve:filter_group(744): pickleshare: pruned from 32 -> 30
DEBUG conda.resolve:filter_group(744): python: pruned from 328 -> 320
Examining conflict for transformers python pytorch tqdm numpy ipykernel pytest seaborn diffusers accelerate wandb pytest-env flake8 torchvision ipdb pip tensorboard: : 27it [13:22, 24Examining conflict for transformers python pytorch tqdm numpy ipykernel pytest seaborn diffusers accelerate wandb pytest-env flake8 torchvision ipdb pip tensorboard: : 28it [13:22, 23Examining conflict for transformers python pytorch pytest ipykernel seaborn diffusers accelerate xformers wandb pytest-env flake8 torchvision ipdb pip tensorboard: : 28it [14:15, 23.0Examining conflict for transformers python pytorch pytest ipykernel seaborn diffusers accelerate xformers wandb pytest-env flake8 torchvision ipdb pip tensorboard: : 29it [14:15, 31.9Examining conflict for transformers pytorch accelerate diffusers torchvision: : 29it [14:51, 31.95s/it]                                                                                failed                                                                                                                                   
DEBUG conda.core.solve:solve_final_state(296): solving prefix /opt/conda/envs/diffusion-classifier
  specs_to_remove: frozenset()
  specs_to_add: frozenset({MatchSpec("python=3.9"), MatchSpec("pytorch[version='>=1.11.0']"), MatchSpec("seaborn"), MatchSpec("pip"), MatchSpec("transformers[version='>=4.14.1']"), MatchSpec("tqdm"), MatchSpec("diffusers"), MatchSpec("accelerate"), MatchSpec("xformers::xformers"), MatchSpec("torchvision[version='>=0.12.0']"), MatchSpec("numpy"), MatchSpec("ipykernel"), MatchSpec("wandb"), MatchSpec("cuda-nvcc"), MatchSpec("tensorboard"), MatchSpec("pytest"), MatchSpec("pytest-env"), MatchSpec("nvidia::cudatoolkit"), MatchSpec("flake8"), MatchSpec("ipdb")})
  prune: False
Solving environment: ...working... DEBUG conda.core.solve:_add_specs(822): specs_map with targets: {'__archspec': MatchSpec("__archspec"), '__cuda': MatchSpec("__cuda"), '__glibc': MatchSpec("__glibc"), '__linux': MatchSpec("__linux"), '__unix': MatchSpec("__unix"), 'python': MatchSpec("python=3.9"), 'pytorch': MatchSpec("pytorch[version='>=1.11.0']"), 'seaborn': MatchSpec("seaborn"), 'pip': MatchSpec("pip"), 'transformers': MatchSpec("transformers[version='>=4.14.1']"), 'tqdm': MatchSpec("tqdm"), 'diffusers': MatchSpec("diffusers"), 'accelerate': MatchSpec("accelerate"), 'xformers': MatchSpec("xformers::xformers"), 'torchvision': MatchSpec("torchvision[version='>=0.12.0']"), 'numpy': MatchSpec("numpy"), 'ipykernel': MatchSpec("ipykernel"), 'wandb': MatchSpec("wandb"), 'cuda-nvcc': MatchSpec("cuda-nvcc"), 'tensorboard': MatchSpec("tensorboard"), 'pytest': MatchSpec("pytest"), 'pytest-env': MatchSpec("pytest-env"), 'cudatoolkit': MatchSpec("nvidia::cudatoolkit"), 'flake8': MatchSpec("flake8"), 'ipdb': MatchSpec("ipdb")}

**Comment by zzou-cn** [comment]
Finally it finishes running and gives me a lot of messages of package conflicts, here are some of them:

Package libwebp conflicts for:
torchvision[version='>=0.12.0'] -> pillow[version='>=5.3.0,!=8.3.*'] -> libwebp[version='>=0.3.0|>=1.2.0,<1.3.0a0']
diffusers -> pillow -> libwebp[version='>=0.3.0|>=1.2.0,<1.3.0a0']

Package decorator conflicts for:
ipdb -> decorator
ipykernel -> ipython[version='>=7.23.1'] -> decorator
pytorch[version='>=1.11.0'] -> networkx -> decorator[version='>=3.4.0|>=4.3.0|>=4.3.0,<5|>=4.1.0']

Package libpng conflicts for:
seaborn -> matplotlib-base[version='>=2.1.2'] -> libpng[version='>=1.6.23,<1.7|>=1.6.32,<1.7.0a0|>=1.6.34,<1.7.0a0|>=1.6.35,<1.7.0a0|>=1.6.37,<1.7.0a0|>=1.6.36,<1.7.0a0']
torchvision[version='>=0.12.0'] -> libpng[version='>=1.6.37,<1.7.0a0|>=1.6.39,<1.7.0a0']

Package requests conflicts for:
transformers[version='>=4.14.1'] -> datasets -> requests[version='>=2.19.0']
transformers[version='>=4.14.1'] -> requests

Package matplotlib conflicts for:
seaborn -> matplotlib[version='>=1.4.3|>=2.1.2|>=2.2']
pytorch[version='>=1.11.0'] -> networkx -> matplotlib[version='>=3.3']

Package libjpeg-turbo conflicts for:
torchvision[version='>=0.12.0'] -> pillow[version='>=5.3.0,!=8.3.*'] -> libjpeg-turbo[version='>=2.1.4,<3.0a0']
torchvision[version='>=0.12.0'] -> libjpeg-turbo[version='>=2.1.5.1,<3.0a0']

Package click conflicts for:
transformers[version='>=4.14.1'] -> sacremoses -> click
tensorboard -> google-auth-oauthlib[version='>=0.5,<1.1'] -> click[version='>=6.0.0']
wandb -> click[version='>=7.0|>=7.0,!=8.0.0|>=7.0,<8']

Package toml conflicts for:
ipdb -> toml[version='>=0.10.2']
pytest-env -> pytest[version='>=2.6.0'] -> toml
pytest -> toml

Package backports conflicts for:
flake8 -> configparser -> backports
wandb -> configparser[version='>=3.8.1'] -> backports

Package aiohttp conflicts for:
transformers[version='>=4.14.1'] -> datasets -> aiohttp
tensorboard -> google-auth[version='>=1.6.3,<3'] -> aiohttp[version='>=3.6.2,<4.0.0dev']The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__cuda==11.4=0
  - feature:/linux-64::__glibc==2.31=0
  - feature:/linux-64::__linux==4.15.0=0
  - feature:/linux-64::__unix==0=0
  - feature:|@/linux-64::__cuda==11.4=0
  - feature:|@/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__linux==4.15.0=0
  - feature:|@/linux-64::__unix==0=0
  - accelerate -> pytorch[version='>=1.6.0'] -> __cuda
  - accelerate -> pytorch[version='>=1.6.0'] -> __glibc[version='>=2.17|>=2.17,<3.0.a0']
  - cuda-nvcc -> cuda-nvcc_linux-64=12.0.76 -> __glibc[version='>=2.17,<3.0.a0']
  - diffusers -> pytorch[version='>=1.4'] -> __cuda
  - diffusers -> pytorch[version='>=1.4'] -> __glibc[version='>=2.17|>=2.17,<3.0.a0']
  - ipdb -> ipython -> __linux
  - ipdb -> ipython -> __win
  - ipykernel -> __linux
  - ipykernel -> __osx
  - ipykernel -> __win
  - numpy -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - nvidia::cudatoolkit -> __glibc[version='>=2.17,<3.0.a0']
  - nvidia::cudatoolkit -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - python=3.9 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - tensorboard -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - torchvision[version='>=0.12.0'] -> __glibc[version='>=2.17|>=2.17,<3.0.a0']
  - torchvision[version='>=0.12.0'] -> pytorch==2.0.0 -> __cuda
  - transformers[version='>=4.14.1'] -> pytorch -> __cuda
  - transformers[version='>=4.14.1'] -> pytorch -> __glibc[version='>=2.17|>=2.17,<3.0.a0']
  - wandb -> click[version='>=7.0,!=8.0.0'] -> __unix
  - wandb -> click[version='>=7.0,!=8.0.0'] -> __win
  - xformers::xformers -> pytorch=1.13.1 -> __cuda
  - xformers::xformers -> pytorch=1.13.1 -> __glibc[version='>=2.17|>=2.17,<3.0.a0']

Your installed version is: 2.31

Note that strict channel priority may have removed packages required for satisfiability.

**Comment by georgefairs** [comment]
@zzou-cn I used mamba instead of conda and it worked fine.

**Comment by alexlioralexli** [comment]
@zzou-cn Did you try mamba? You can also use the libmamba solver within conda (setup instructions [here](https://conda.github.io/conda-libmamba-solver/getting-started/)). I think this should work with `conda config --set channel_priority flexible`
